require('basic')
require('keybindings')
require('plugins')
require('colorscheme')
require('toggleterm-config')
require('nvim-tree-config')
require('bufferline-config')
require('lualine-config')
require('telescope-config')
require('dashboard-nvim-config')
require('nvim-treesitter-config')
-- require('lsp.setup')
